# Generated by Django 4.1.2 on 2022-10-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
    ]
