# Generated by Django 4.1.3 on 2022-11-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
