# Generated by Django 4.1.3 on 2022-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_gameserverinstance_current_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserverinstance',
            name='server_auth_token',
            field=models.UUIDField(default='4e7cb2a0-2153-4f27-8033-bcdb78777adb'),
            preserve_default=False,
        ),
    ]
