# Generated by Django 4.1.3 on 2022-11-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_alter_gameserverinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserverinstance',
            name='server_auth_token',
        ),
    ]
